import {
    AlertTriangle,
    ArrowRight,
    Check,
    ChevronLeft,
    ChevronRight,
    Command,
    CreditCard,
    File,
    FileText,
    HelpCircle,
    Image,
    Laptop,
    Loader2,
    Moon,
    MoreVertical,
    Pizza,
    Plus,
    Settings,
    Sun,
    Trash,
    Twitter,
    User,
    X,
    Mail,
    Lock,
    Eye,
    EyeOff,
    Calendar,
    Clock,
    Video,
    Mic,
    MicOff,
    VideoOff,
    MoreHorizontal,
    Phone,
    PhoneOff,
    Monitor,
    Share,
    MessageSquare,
    Search,
    Users,
    LogOut,
    Menu,
    Home,
    LayoutDashboard,
    Bell,
} from "lucide-react"

export const Icons = {
    logo: Command,
    close: X,
    spinner: Loader2,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    trash: Trash,
    post: FileText,
    page: File,
    media: Image,
    settings: Settings,
    billing: CreditCard,
    ellipsis: MoreVertical,
    add: Plus,
    warning: AlertTriangle,
    user: User,
    arrowRight: ArrowRight,
    help: HelpCircle,
    pizza: Pizza,
    sun: Sun,
    moon: Moon,
    laptop: Laptop,
    twitter: Twitter,
    check: Check,
    mail: Mail,
    lock: Lock,
    eye: Eye,
    eyeOff: EyeOff,
    calendar: Calendar,
    clock: Clock,
    video: Video,
    mic: Mic,
    micOff: MicOff,
    videoOff: VideoOff,
    moreHorizontal: MoreHorizontal,
    phone: Phone,
    phoneOff: PhoneOff,
    monitor: Monitor,
    share: Share,
    message: MessageSquare,
    search: Search,
    users: Users,
    logout: LogOut,
    menu: Menu,
    home: Home,
    dashboard: LayoutDashboard,
    bell: Bell,
}
